// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
        
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBORKVa5oulXRN-E0OBIm16GHcBo_M7hP4',
    appId: '1:943543278295:web:88855d0111efd0fd55ae92',
    messagingSenderId: '943543278295',
    projectId: 'recycleview-fd7a9',
    authDomain: 'recycleview-fd7a9.firebaseapp.com',
    storageBucket: 'recycleview-fd7a9.appspot.com',
    measurementId: 'G-9QQEMZLQMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCBGOOiaMrzC1UlDREjTnYypw48SKu8h4',
    appId: '1:943543278295:android:1e0065402bda073655ae92',
    messagingSenderId: '943543278295',
    projectId: 'recycleview-fd7a9',
    storageBucket: 'recycleview-fd7a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1UlBPWyKTzquPVfiBEqUIRFUrVVOcr2c',
    appId: '1:943543278295:ios:434cce27d3f5b13b55ae92',
    messagingSenderId: '943543278295',
    projectId: 'recycleview-fd7a9',
    storageBucket: 'recycleview-fd7a9.appspot.com',
    iosClientId: '943543278295-nj3mod26sdqv6mopvvo29k33lqbo70fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.recycleView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1UlBPWyKTzquPVfiBEqUIRFUrVVOcr2c',
    appId: '1:943543278295:ios:61907e6c122e5f6255ae92',
    messagingSenderId: '943543278295',
    projectId: 'recycleview-fd7a9',
    storageBucket: 'recycleview-fd7a9.appspot.com',
    iosClientId: '943543278295-ufdqu2epr6m3ff7p13jigssed5h6f0uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.recycleView.RunnerTests',
  );
}
